CREATE TABLE "RL_AMP_AMP_BR"
  (
    "CO_SEQ_ID"  NUMBER(10) NOT NULL,
    "CO_SRCAPID" NUMBER(10) NOT NULL,
    "CO_DSTAPID" NUMBER(10) NOT NULL,
    "DT_PUBLIC"  NUMBER(15) NOT NULL
  ) ;
CREATE TABLE "RL_AMP_INGREDIENT_SUBST_BR"
  (
    "CO_SEQ_ID" NUMBER(10) NOT NULL,
    "CO_APID"   NUMBER(10) NOT NULL,
    "CO_ISID"   NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_AMP_PRESERV_COND_BR"
  (
    "CO_SEQ_ID"        NUMBER(10) NOT NULL,
    "CO_APID"          NUMBER(10) NOT NULL,
    "CO_PRESERVCONDCD" NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_AMP_ROUTE"
  (
    "CO_SEQ_ID"  NUMBER(10) NOT NULL,
    "CO_ROUTECD" NUMBER(10) NOT NULL,
    "CO_APID"    NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_AMPP_AMPP"
  (
    "CO_SEQ_ID"    NUMBER(10) NOT NULL,
    "CO_CHLDAPPID" NUMBER(10) NOT NULL,
    "CO_PRNTAPPID" NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_AMPP_HEALTHCARE_PROF_BR"
  (
    "CO_SEQ_ID"    NUMBER(10) NOT NULL,
    "CO_APPID"     NUMBER(10) NOT NULL,
    "CO_HPROFBRID" NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_AMPP_SUPPLIER_BR"
  (
    "CO_SEQ_ID" NUMBER(10) NOT NULL,
    "CO_APPID"  NUMBER(10) NOT NULL,
    "CO_SUPPCD" NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_RENAME_INGREDIENT_SUBST_BR"
  (
    "CO_SEQ_ID"   NUMBER(10) NOT NULL,
    "CO_RENAMEID" NUMBER(10) NOT NULL,
    "CO_ISID"     NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_RENAME_RENAME_COMP_BR"
  (
    "CO_SEQ_ID"       NUMBER(10) NOT NULL,
    "CO_RENAMEID"     NUMBER(10) NOT NULL,
    "CO_RENAMECOMPCD" NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_VMP_CONTROL_DRUG_INFO"
  (
    "CO_SEQ_ID"     NUMBER(10) NOT NULL,
    "CO_VPID"       NUMBER(10) NOT NULL,
    "CO_CATCD"      NUMBER(10) NOT NULL,
    "DT_CATDT"      NUMBER(15) NULL,
    "CO_CAT_PREVCD" NUMBER(10) NULL
  ) ;
CREATE TABLE "RL_VMP_FORM"
  (
    "CO_SEQ_ID" NUMBER(10) NOT NULL,
    "CO_FORMCD" NUMBER(10) NOT NULL,
    "CO_VPID"   NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_VMP_ONT_FORM_ROUTE"
  (
    "CO_SEQ_ID" NUMBER(10) NOT NULL,
    "CO_FORMCD" NUMBER(10) NOT NULL,
    "CO_VPID"   NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_VMP_RENAME_BR"
  (
    "CO_SEQ_ID"   NUMBER(10) NOT NULL,
    "CO_VPID"     NUMBER(10) NOT NULL,
    "CO_RENAMEID" NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_VMP_ROUTE"
  (
    "CO_SEQ_ID"  NUMBER(10) NOT NULL,
    "CO_ROUTECD" NUMBER(10) NOT NULL,
    "CO_VPID"    NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_VMPP_VMPP"
  (
    "CO_SEQ_ID"    NUMBER(10) NOT NULL,
    "CO_CHLDVPPID" NUMBER(10) NOT NULL,
    "CO_PRNTVPPID" NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RL_VTM_INGREDIENT_SUBST_BR"
  (
    "CO_SEQ_ID" NUMBER(10) NOT NULL,
    "CO_VTMID"  NUMBER(10) NOT NULL,
    "CO_ISID"   NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "RT_AMP_INGREDIENT_SUBST"
  (
    "CO_SEQ_ID" NUMBER(10) NOT NULL,
    "CO_ISID"   NUMBER(10) NOT NULL,
    "CO_APID"   NUMBER(10) NOT NULL,
    "QT_STRNTH" NUMBER(10,3) NULL,
    "CO_UOMCD"  NUMBER(10) NULL
  ) ;
CREATE TABLE "RT_RENAME_BR"
  (
    "CO_SEQ_ID"    NUMBER(10) NOT NULL,
    "CO_FFACD"     NUMBER(10) NULL,
    "DS_DOCNORT"   VARCHAR2(1000 BYTE) NULL,
    "DS_ANNEX"     VARCHAR2(10 BYTE) NULL,
    "DS_CONC"      VARCHAR2(50 BYTE) NULL,
    "DS_GENERICDN" VARCHAR2(100 BYTE) NULL
  ) ;
CREATE TABLE "RT_VMP_INGREDIENT_SUBST"
  (
    "CO_SEQ_ID"            NUMBER(10) NOT NULL,
    "CO_ISID"              NUMBER(10) NOT NULL,
    "CO_VPID"              NUMBER(10) NOT NULL,
    "CO_BS_SUBID"          NUMBER(10) NULL,
    "CO_BASIS_STRNTCD"     NUMBER(10) NOT NULL,
    "QT_STRNT_NMRTR_VAL"   NUMBER(10,3) NOT NULL,
    "CO_STRNT_NMRTR_UOMCD" NUMBER(10) NOT NULL,
    "QT_STRNT_DNMTR_VAL"   NUMBER(10,3) NULL,
    "CO_STRNT_DNMTR_UOMCD" NUMBER(10) NULL
  ) ;
CREATE TABLE "TB_AMP"
  (
    "CO_SEQ_ID"               NUMBER(10) NOT NULL,
    "NU_APID"                 VARCHAR2(18 BYTE) NOT NULL,
    "ST_INVALID"              NUMBER(1) NULL,
    "CO_VPID"                 NUMBER(10) NOT NULL,
    "ST_COMBPRODCD"           NUMBER(1) NULL,
    "NO_NM"                   VARCHAR2(255 BYTE) NOT NULL,
    "DS_DESCR"                VARCHAR2(700 BYTE) NOT NULL,
    "DT_NMDT"                 NUMBER(15) NULL,
    "NO_NM_PREV"              VARCHAR2(255 BYTE) NULL,
    "NO_ABBREVNM"             VARCHAR2(60 BYTE) NULL,
    "CO_SUPPCD"               NUMBER(10) NOT NULL,
    "CO_FLAVOURCD"            NUMBER(10) NULL,
    "ST_PARALLEL_IMPORT"      NUMBER(1) NULL,
    "CO_LIC_AUTHCD"           NUMBER(10) NOT NULL,
    "CO_LIC_AUTH_PREVCD"      NUMBER(10) NULL,
    "DT_LIC_AUTHCHANGEDT"     NUMBER(15) NULL,
    "CO_LIC_AUTHCHANGECD"     NUMBER(10) NULL,
    "CO_AVAIL_RESTRICTCD"     NUMBER(10) NOT NULL,
    "CO_MEDCLSCD"             NUMBER(10) NOT NULL,
    "CO_MONITORINGREASONCD"   NUMBER(10) NULL,
    "ST_ENTERALTUBESADMIN"    NUMBER(1) NULL,
    "DS_ENTERALTUBESADMINOBS" VARCHAR2(500 BYTE) NULL,
    "NU_NREG"                 NUMBER(9) NULL,
    "NU_NPROC"                VARCHAR2(20 BYTE) NULL,
    "NU_VENCREG"              VARCHAR2(7 BYTE) NOT NULL,
    "NU_VALIDITY"             NUMBER(3) NULL,
    "CO_VALIDITYUNIT"         VARCHAR2(10 BYTE) NULL
  ) ;
CREATE TABLE "TB_AMPP"
  (
    "CO_SEQ_ID"       NUMBER(10) NOT NULL,
    "NU_APPID"        VARCHAR2(18 BYTE) NOT NULL,
    "ST_INVALID"      NUMBER(1) NULL,
    "CO_VPPID"        NUMBER(10) NOT NULL,
    "NO_NM"           VARCHAR2(774 BYTE) NOT NULL,
    "CO_APID"         NUMBER(10) NOT NULL,
    "DS_SUBP"         VARCHAR2(30 BYTE) NULL,
    "ST_COMBPACKCD"   NUMBER(1) NULL,
    "CO_LEGAL_CATCD"  NUMBER(10) NOT NULL,
    "CO_DISCCD"       NUMBER(10) NULL,
    "DT_DISCDT"       NUMBER(15) NULL,
    "DS_PRIMARYPCK"   VARCHAR2(200 BYTE) NULL,
    "DS_SECONDARYPCK" VARCHAR2(200 BYTE) NULL,
    "NU_SANREG"       NUMBER(13) NOT NULL,
    "DT_REGPUBLIC"    NUMBER(15) NOT NULL,
    "ST_HOSP"         NUMBER(1,2) NULL
  ) ;
CREATE TABLE "TB_AMPP_GTIN"
  (
    "CO_SEQ_ID"  NUMBER(10) NOT NULL,
    "CO_APPID"   NUMBER(10) NOT NULL,
    "NU_GTININD" NUMBER(14) NOT NULL
  ) ;
CREATE TABLE "TB_VMP"
  (
    "CO_SEQ_ID"          NUMBER(10) NOT NULL,
    "NU_VPID"            VARCHAR2(18 BYTE) NOT NULL,
    "DT_VPIDDT"          NUMBER(15) NULL,
    "CO_VPIDPREV"        NUMBER(10) NULL,
    "ST_INVALID"         NUMBER(1) NULL,
    "CO_VTMID"           NUMBER(10) NULL,
    "ST_COMBPRODCD"      NUMBER(1) NULL,
    "NO_NM"              VARCHAR2(255 BYTE) NOT NULL,
    "CO_BASISCD"         NUMBER(10) NOT NULL,
    "DT_NMDT"            NUMBER(15) NULL,
    "NO_NMPREV"          VARCHAR2(255 BYTE) NULL,
    "CO_BASIS_PREVCD"    NUMBER(10) NULL,
    "CO_NMCHANGECD"      NUMBER(10) NULL,
    "NO_ABBREVNM"        VARCHAR2(60 BYTE) NULL,
    "ST_SUG_F"           NUMBER(1) NULL,
    "ST_GLU_F"           NUMBER(1) NULL,
    "ST_PRES_F"          NUMBER(1) NULL,
    "ST_CFC_FREE"        NUMBER(1) NULL,
    "CO_PRES_STATCD"     NUMBER(10) NOT NULL,
    "CO_NON_AVAILCD"     NUMBER(10) NULL,
    "DT_NON_AVAILDT"     NUMBER(15) NULL,
    "CO_DF_INDCD"        NUMBER(10) NOT NULL,
    "QT_UDFS"            NUMBER(10,3) NULL,
    "CO_UDFS_UOMCD"      NUMBER(10) NULL,
    "CO_UNIT_DOSE_UOMCD" NUMBER(10) NULL,
    "ST_FTN"             NUMBER(1) NULL,
    "ST_HORUS"           NUMBER(1) NULL,
    "DS_NOTIFICATION"    VARCHAR2(250 BYTE) NULL,
    "CO_ATCCLSCD"        NUMBER(10) NULL,
    "CO_ANVSCLSCD"       NUMBER(10) NULL
  ) ;
CREATE TABLE "TB_VMP_CATMAT_BR"
  (
    "CO_SEQ_ID"   NUMBER(10) NOT NULL,
    "CO_VPID"     NUMBER(10) NOT NULL,
    "CO_CATMATCD" VARCHAR2(20 BYTE) NOT NULL,
    "NO_HORUS"    VARCHAR2(255) NULL,
    "ST_INVALID"  NUMBER(1) NULL
  ) ;
CREATE TABLE "TB_VMPP"
  (
    "CO_SEQ_ID"     NUMBER(10) NOT NULL,
    "NU_VPPID"      VARCHAR2(18 BYTE) NOT NULL,
    "ST_INVALID"    NUMBER(1) NULL,
    "CO_VPID"       NUMBER(10) NOT NULL,
    "NO_NM"         VARCHAR2(420 BYTE) NOT NULL,
    "ST_COMBPACKCD" NUMBER(1) NULL,
    "QT_QTYVAL"     NUMBER(10,3) NOT NULL,
    "CO_QTY_UOMCD"  NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "TB_VMPP_CATMAT_BR"
  (
    "CO_SEQ_ID"   NUMBER(10) NOT NULL,
    "CO_VPPID"    NUMBER(10) NOT NULL,
    "CO_CATMATCD" VARCHAR2(20 BYTE) NOT NULL,
    "NO_HORUS"    VARCHAR2(255) NULL,
    "ST_INVALID"  NUMBER(1) NULL
  ) ;
CREATE TABLE "TB_VTM"
  (
    "CO_SEQ_ID"    NUMBER(10) NOT NULL,
    "NU_VTMID"     VARCHAR2(18 BYTE) NOT NULL,
    "DT_VTMIDDT"   NUMBER(15) NULL,
    "CO_VTMIDPREV" NUMBER(10) NULL,
    "ST_INVALID"   NUMBER(1) NULL,
    "NO_NM"        VARCHAR2(255 BYTE) NOT NULL,
    "NO_ABBREVNM"  VARCHAR2(60 BYTE) NULL
  ) ;
CREATE TABLE "TD_ANVS_CLASS_BR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_ATC_CLASS_BR"
  (
    "CO_SEQ_ID"          NUMBER(10) NOT NULL,
    "NU_CD"              VARCHAR2(10 BYTE) NOT NULL,
    "NO_DESCR"           VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR"     VARCHAR2(500 BYTE) NULL,
    "CO_PARENT"          NUMBER(10) NULL,
    "ST_HIERARCHY_LEVEL" NUMBER(1) NULL
  ) ;
CREATE TABLE "TD_AVAILABILITY_RESTRICTION"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_BASIS_OF_NAME"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_BASIS_OF_STRNTH"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_CONTROL_DRUG_CATEGORY"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL,
    "DS_SCOPE"       VARCHAR2(250 BYTE) NULL,
    "DS_LIMITPRESC"  VARCHAR2(250 BYTE) NULL,
    "DS_QTYPRESC"    VARCHAR2(50 BYTE) NULL,
    "DS_VALPRESC"    VARCHAR2(50 BYTE) NULL
  ) ;
CREATE TABLE "TD_COUNTRY"
  (
    "CO_SEQ_ID"                NUMBER(10) NOT NULL,
    "NU_CD"                    VARCHAR2(3 BYTE) NOT NULL,
    "NO_DESCR"                 VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR"           VARCHAR2(500 BYTE) NULL,
    "AU_AUDIT_CREATE_DATETIME" NUMBER(15) NOT NULL,
    "AU_AUDIT_CHANGE_DATETIME" NUMBER(15) NOT NULL,
    "AU_AUDIT_CREATE_USERNAME" VARCHAR2(50 BYTE) NOT NULL,
    "AU_AUDIT_CHANGE_USERNAME" VARCHAR2(50 BYTE) NOT NULL,
    "NU_VERSION"               NUMBER(3) NOT NULL,
    "ST_REGISTRO_ATIVO"        VARCHAR2(100 BYTE) DEFAULT 'ACTIVE' NOT NULL
  ) ;
CREATE TABLE "TD_DF_INDICATOR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_DISCONTINUED_IND"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_FLAVOUR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_FORM"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "DT_CDDT"        NUMBER(15) NULL,
    "CO_CDPREV"      NUMBER(10) NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL,
    "NO_ABBREVNM"    VARCHAR2(60 BYTE) NULL,
    "CO_FFACD"       NUMBER(10) NULL
  ) ;
CREATE TABLE "TD_HEALTHCARE_PROF_BR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_INGREDIENT_SOURCE_BR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_INGREDIENT_SUBSTANCES"
  (
    "CO_SEQ_ID"   NUMBER(10) NOT NULL,
    "NU_ISID"     VARCHAR2(18 BYTE) NOT NULL,
    "DT_ISIDDT"   NUMBER(15) NULL,
    "CO_ISIDPREV" NUMBER(10) NULL,
    "ST_INVALID"  NUMBER(1) NULL,
    "NO_NM"       VARCHAR2(255 BYTE) NOT NULL,
    "NO_NM_PT_BR" VARCHAR2(255 BYTE) NOT NULL,
    "CO_ISRCID"   NUMBER(10) NOT NULL,
    "CO_DCBCD"    VARCHAR2(5 BYTE) NULL,
    "CO_NCAS"     VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_LEGAL_CATEGORY"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_LIC_AUTH_CHANGE_REASON"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_LICENSING_AUTHORITY"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_MED_CLASS_BR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_MONITORING_REASON_BR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_NAME_CHANGE_REASON"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_ONT_FORM_ROUTE"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_PRESERV_COND_BR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_RENAME_COMP_BR"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NULL
  ) ;
CREATE TABLE "TD_ROUTE"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "DT_CDDT"        NUMBER(15) NULL,
    "CO_CDPREV"      NUMBER(10) NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_SUPPLIER"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "DT_CDDT"        NUMBER(15) NULL,
    "CO_CDPREV"      NUMBER(10) NULL,
    "ST_INVALID"     NUMBER(1) NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NU_CNPJ"        VARCHAR2(20 BYTE) NOT NULL,
    "NU_NAUTH"       NUMBER(9) NULL,
    "CO_COUNTRYCD"   NUMBER(10) NOT NULL
  ) ;
CREATE TABLE "TD_UNIT_OF_MEASURE"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "DT_CDDT"        NUMBER(15) NULL,
    "CO_CDPREV"      NUMBER(10) NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL,
    "ST_SPPLYUNIT"   VARCHAR2(10 BYTE) NULL
  ) ;
CREATE TABLE "TD_VIRTUAL_PRODUCT_NON_AVAIL"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
CREATE TABLE "TD_VIRTUAL_PRODUCT_PRES_STATUS"
  (
    "CO_SEQ_ID"      NUMBER(10) NOT NULL,
    "NU_CD"          VARCHAR2(18 BYTE) NOT NULL,
    "NO_DESCR"       VARCHAR2(500 BYTE) NOT NULL,
    "NO_DESCR_PT_BR" VARCHAR2(500 BYTE) NOT NULL
  ) ;
ALTER TABLE "RL_AMP_AMP_BR" ADD CONSTRAINT "PK_AMP_AMP_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_INGREDIENT_SUBST_BR" ADD CONSTRAINT "PK_AMP_INGREDIENT_SUBST_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_PRESERV_COND_BR" ADD CONSTRAINT "PK_AMP_PRESERV_COND_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_ROUTE" ADD CONSTRAINT "PK_AMP_ROUTE" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_AMPP" ADD CONSTRAINT "PK_AMPP_AMPP" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_HEALTHCARE_PROF_BR" ADD CONSTRAINT "PK_AMPP_HEALTHCARE_PROF_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_SUPPLIER_BR" ADD CONSTRAINT "PK_AMPP_SUPPLIER_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_RENAME_INGREDIENT_SUBST_BR" ADD CONSTRAINT "PK_RENAME_INGREDIENT_SUBST_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_RENAME_RENAME_COMP_BR" ADD CONSTRAINT "PK_RENAME_RENAME_COMP_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_CONTROL_DRUG_INFO" ADD CONSTRAINT "PK_CONTROL_DRUG_INFO" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_FORM" ADD CONSTRAINT "PK_VMP_FORM" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_ONT_FORM_ROUTE" ADD CONSTRAINT "PK_VMP_ONT_FORM_ROUTE" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_RENAME_BR" ADD CONSTRAINT "PK_VMP_RENAME_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_ROUTE" ADD CONSTRAINT "PK_VMP_ROUTE" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMPP_VMPP" ADD CONSTRAINT "PK_VMPP_VMPP" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_VTM_INGREDIENT_SUBST_BR" ADD CONSTRAINT "PK_VTM_INGREDIENT_SUBST_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RT_AMP_INGREDIENT_SUBST" ADD CONSTRAINT "PK_AMP_INGREDIENT_SUBST" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RT_RENAME_BR" ADD CONSTRAINT "PK_RENAME_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RT_VMP_INGREDIENT_SUBST" ADD CONSTRAINT "PK_VMP_INGREDIENT_SUBST" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "PK_AMP" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMPP" ADD CONSTRAINT "PK_AMPP" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMPP_GTIN" ADD CONSTRAINT "PK_GTIN" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "PK_VMP" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP_CATMAT_BR" ADD CONSTRAINT "PK_VMP_CATMAT_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMPP" ADD CONSTRAINT "PK_VMPP" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMPP_CATMAT_BR" ADD CONSTRAINT "PK_VMPP_CATMAT_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TB_VTM" ADD CONSTRAINT "PK_VTM" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_ANVS_CLASS_BR" ADD CONSTRAINT "PK_ANVS_CLASS_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_ATC_CLASS_BR" ADD CONSTRAINT "PK_ATC_CLASS_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_AVAILABILITY_RESTRICTION" ADD CONSTRAINT "PK_AVAILABILITY_RESTRICTION" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_BASIS_OF_NAME" ADD CONSTRAINT "PK_BASIS_OF_NAME" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_BASIS_OF_STRNTH" ADD CONSTRAINT "PK_BASIS_OF_STRNTH" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_CONTROL_DRUG_CATEGORY" ADD CONSTRAINT "PK_CONTROL_DRUG_CATEGORY" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_COUNTRY" ADD CONSTRAINT "PK_COUNTRY" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_DF_INDICATOR" ADD CONSTRAINT "PK_DF_INDICATOR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_DISCONTINUED_IND" ADD CONSTRAINT "PK_DISCONTINUED_IND" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_FLAVOUR" ADD CONSTRAINT "PK_FLAVOUR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_FORM" ADD CONSTRAINT "PK_FORM" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_HEALTHCARE_PROF_BR" ADD CONSTRAINT "PK_HEALTHCARE_PROF_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_INGREDIENT_SOURCE_BR" ADD CONSTRAINT "PK_INGREDIENT_SOURCE_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_INGREDIENT_SUBSTANCES" ADD CONSTRAINT "PK_INGREDIENT_SUBSTANCES" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_LEGAL_CATEGORY" ADD CONSTRAINT "PK_LEGAL_CATEGORY" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_LIC_AUTH_CHANGE_REASON" ADD CONSTRAINT "PK_LIC_AUTH_CHANGE_REASON" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_LICENSING_AUTHORITY" ADD CONSTRAINT "PK_LICENSING_AUTHORITY" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_MED_CLASS_BR" ADD CONSTRAINT "PK_MED_CLASS_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_MONITORING_REASON_BR" ADD CONSTRAINT "PK_MONITORING_REASON_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_NAME_CHANGE_REASON" ADD CONSTRAINT "PK_NAME_CHANGE_REASON" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_ONT_FORM_ROUTE" ADD CONSTRAINT "PK_ONT_FORM_ROUTE" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_PRESERV_COND_BR" ADD CONSTRAINT "PK_PRESERV_COND_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_RENAME_COMP_BR" ADD CONSTRAINT "PK_RENAME_COMP_BR" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_ROUTE" ADD CONSTRAINT "PK_ROUTE" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_SUPPLIER" ADD CONSTRAINT "PK_SUPPLIER" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_UNIT_OF_MEASURE" ADD CONSTRAINT "PK_UNIT_OF_MEASURE" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_VIRTUAL_PRODUCT_NON_AVAIL" ADD CONSTRAINT "PK_VIRTUAL_PRODUCT_NON_AVAIL" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "TD_VIRTUAL_PRODUCT_PRES_STATUS" ADD CONSTRAINT "PK_VIRTUAL_PRODUCT_PRES_STATUS" PRIMARY KEY ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_AMP_BR" ADD CONSTRAINT "FK_AMP_AMP_AMP_DST" FOREIGN KEY ("CO_DSTAPID") REFERENCES "TB_AMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_AMP_BR" ADD CONSTRAINT "FK_AMP_AMP_AMP_SRC" FOREIGN KEY ("CO_SRCAPID") REFERENCES "TB_AMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_INGREDIENT_SUBST_BR" ADD CONSTRAINT "FK_AMP_IGR_SUBST_BR_IGR_SUBST" FOREIGN KEY ("CO_ISID") REFERENCES "TD_INGREDIENT_SUBSTANCES" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_INGREDIENT_SUBST_BR" ADD CONSTRAINT "FK_AMP_INGREDIENT_SUBST_BR_AMP" FOREIGN KEY ("CO_APID") REFERENCES "TB_AMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_PRESERV_COND_BR" ADD CONSTRAINT "FK_AMP_PRESERV_COND_BR_AMP" FOREIGN KEY ("CO_APID") REFERENCES "TB_AMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_PRESERV_COND_BR" ADD CONSTRAINT "FK_AMP_PRSV_CND_BR_PRSV_CND_BR" FOREIGN KEY ("CO_PRESERVCONDCD") REFERENCES "TD_PRESERV_COND_BR" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_ROUTE" ADD CONSTRAINT "FK_AMP_ROUTE_AMP" FOREIGN KEY ("CO_APID") REFERENCES "TB_AMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMP_ROUTE" ADD CONSTRAINT "FK_AMP_ROUTE_ROUTE" FOREIGN KEY ("CO_ROUTECD") REFERENCES "TD_ROUTE" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_AMPP" ADD CONSTRAINT "FK_AMPP_AMPP_CHLD" FOREIGN KEY ("CO_CHLDAPPID") REFERENCES "TB_AMPP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_AMPP" ADD CONSTRAINT "FK_AMPP_AMPP_PRNT" FOREIGN KEY ("CO_PRNTAPPID") REFERENCES "TB_AMPP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_HEALTHCARE_PROF_BR" ADD CONSTRAINT "FK_AMPP_HC_PROF_BR_HC_PROF_BR" FOREIGN KEY ("CO_HPROFBRID") REFERENCES "TD_HEALTHCARE_PROF_BR" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_HEALTHCARE_PROF_BR" ADD CONSTRAINT "FK_AMPP_HEALTHCARE_PRF_BR_AMPP" FOREIGN KEY ("CO_APPID") REFERENCES "TB_AMPP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_SUPPLIER_BR" ADD CONSTRAINT "FK_AMPP_SUPPLIER_BR_AMPP" FOREIGN KEY ("CO_APPID") REFERENCES "TB_AMPP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_AMPP_SUPPLIER_BR" ADD CONSTRAINT "FK_AMPP_SUPPLIER_BR_SUPPLIER" FOREIGN KEY ("CO_SUPPCD") REFERENCES "TD_SUPPLIER" ("CO_SEQ_ID") ;
ALTER TABLE "RL_RENAME_INGREDIENT_SUBST_BR" ADD CONSTRAINT "FK_RNME_INGR_SBST_BR_INGR_SBST" FOREIGN KEY ("CO_ISID") REFERENCES "TD_INGREDIENT_SUBSTANCES" ("CO_SEQ_ID") ;
ALTER TABLE "RL_RENAME_INGREDIENT_SUBST_BR" ADD CONSTRAINT "FK_RNME_INGR_SUBST_BR_RNME_BR" FOREIGN KEY ("CO_RENAMEID") REFERENCES "RT_RENAME_BR" ("CO_SEQ_ID") ;
ALTER TABLE "RL_RENAME_RENAME_COMP_BR" ADD CONSTRAINT "FK_RNM_BR_RNM_CMP_BR" FOREIGN KEY ("CO_RENAMEID") REFERENCES "TD_RENAME_COMP_BR" ("CO_SEQ_ID") ;
ALTER TABLE "RL_RENAME_RENAME_COMP_BR" ADD CONSTRAINT "FK_RNME_RNME_COMP_BR_RNME_BR" FOREIGN KEY ("CO_RENAMEID") REFERENCES "RT_RENAME_BR" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_CONTROL_DRUG_INFO" ADD CONSTRAINT "FK_VMP_CONTROL_DRUG_INFO_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_CONTROL_DRUG_INFO" ADD CONSTRAINT "FK_CTRL_DRUG_CTRL_DRUG_CAT_CD" FOREIGN KEY ("CO_CATCD") REFERENCES "TD_CONTROL_DRUG_CATEGORY" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_CONTROL_DRUG_INFO" ADD CONSTRAINT "FK_CTRL_DRUG_CTRL_DRUG_CAT_PCD" FOREIGN KEY ("CO_CAT_PREVCD") REFERENCES "TD_CONTROL_DRUG_CATEGORY" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_FORM" ADD CONSTRAINT "FK_VMP_FORM_FORM" FOREIGN KEY ("CO_FORMCD") REFERENCES "TD_FORM" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_FORM" ADD CONSTRAINT "FK_VMP_FORM_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_ONT_FORM_ROUTE" ADD CONSTRAINT "FK_VMP_ONT_FORM_ROUTE_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_ONT_FORM_ROUTE" ADD CONSTRAINT "FK_VMP_ONT_FORM_RT_ONT_FORM_RT" FOREIGN KEY ("CO_FORMCD") REFERENCES "TD_ONT_FORM_ROUTE" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_RENAME_BR" ADD CONSTRAINT "FK_VMP_RENAME_BR_RENAME_BR" FOREIGN KEY ("CO_RENAMEID") REFERENCES "RT_RENAME_BR" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_RENAME_BR" ADD CONSTRAINT "FK_VMP_RENAME_BR_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_ROUTE" ADD CONSTRAINT "FK_VMP_ROUTE_ROUTE" FOREIGN KEY ("CO_ROUTECD") REFERENCES "TD_ROUTE" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMP_ROUTE" ADD CONSTRAINT "FK_VMP_ROUTE_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMPP_VMPP" ADD CONSTRAINT "FK_VMPP_VMPP_CHLD" FOREIGN KEY ("CO_CHLDVPPID") REFERENCES "TB_VMPP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VMPP_VMPP" ADD CONSTRAINT "FK_VMPP_VMPP_PRNT" FOREIGN KEY ("CO_PRNTVPPID") REFERENCES "TB_VMPP" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VTM_INGREDIENT_SUBST_BR" ADD CONSTRAINT "FK_VTM_IGR_SUBST_BR_IGR_SUBST" FOREIGN KEY ("CO_ISID") REFERENCES "TD_INGREDIENT_SUBSTANCES" ("CO_SEQ_ID") ;
ALTER TABLE "RL_VTM_INGREDIENT_SUBST_BR" ADD CONSTRAINT "FK_VTM_IGR_SUBST_BR_VTM" FOREIGN KEY ("CO_VTMID") REFERENCES "TB_VTM" ("CO_SEQ_ID") ;
ALTER TABLE "RT_AMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_AMP_INGREDIENT_SUBST" FOREIGN KEY ("CO_ISID") REFERENCES "TD_INGREDIENT_SUBSTANCES" ("CO_SEQ_ID") ;
ALTER TABLE "RT_AMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_AMP_INGREDIENT_SUBST_AMP" FOREIGN KEY ("CO_APID") REFERENCES "TB_AMP" ("CO_SEQ_ID") ;
ALTER TABLE "RT_AMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_AMP_INGREDIENT_SUBST_UOM" FOREIGN KEY ("CO_UOMCD") REFERENCES "TD_UNIT_OF_MEASURE" ("CO_SEQ_ID") ;
ALTER TABLE "RT_RENAME_BR" ADD CONSTRAINT "FK_RENAME_BR_FORM" FOREIGN KEY ("CO_FFACD") REFERENCES "TD_FORM" ("CO_SEQ_ID") ;
ALTER TABLE "RT_VMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_TB_VMP_INGREDIENT_BSSUBID" FOREIGN KEY ("CO_BS_SUBID") REFERENCES "TD_INGREDIENT_SUBSTANCES" ("CO_SEQ_ID") ;
ALTER TABLE "RT_VMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_TB_VMP_INGREDIENT_ISID" FOREIGN KEY ("CO_ISID") REFERENCES "TD_INGREDIENT_SUBSTANCES" ("CO_SEQ_ID") ;
ALTER TABLE "RT_VMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_VMP_INGREDIENT_SUBST_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "RT_VMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_VMP_INGR_SUBST_BS_OF_STRNTH" FOREIGN KEY ("CO_BASIS_STRNTCD") REFERENCES "TD_BASIS_OF_STRNTH" ("CO_SEQ_ID") ;
ALTER TABLE "RT_VMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_VMP_INGR_SUBST_DNMTRUOM" FOREIGN KEY ("CO_STRNT_DNMTR_UOMCD") REFERENCES "TD_UNIT_OF_MEASURE" ("CO_SEQ_ID") ;
ALTER TABLE "RT_VMP_INGREDIENT_SUBST" ADD CONSTRAINT "FK_VMP_INGR_SUBST_NMRTRUOM" FOREIGN KEY ("CO_STRNT_NMRTR_UOMCD") REFERENCES "TD_UNIT_OF_MEASURE" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_AVAILABILIT_RESTRICTION" FOREIGN KEY ("CO_AVAIL_RESTRICTCD") REFERENCES "TD_AVAILABILITY_RESTRICTION" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_FLAVOUR" FOREIGN KEY ("CO_FLAVOURCD") REFERENCES "TD_FLAVOUR" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_LICENSING_AUTHORITY_CD" FOREIGN KEY ("CO_LIC_AUTHCD") REFERENCES "TD_LICENSING_AUTHORITY" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_LICENSING_AUTHORITY_PCD" FOREIGN KEY ("CO_LIC_AUTH_PREVCD") REFERENCES "TD_LICENSING_AUTHORITY" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_LIC_AUTH_CHANGE_REASON" FOREIGN KEY ("CO_LIC_AUTHCHANGECD") REFERENCES "TD_LIC_AUTH_CHANGE_REASON" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_MED_CLASS_BR" FOREIGN KEY ("CO_MEDCLSCD") REFERENCES "TD_MED_CLASS_BR" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_MONITORING_REASON_BR" FOREIGN KEY ("CO_MONITORINGREASONCD") REFERENCES "TD_MONITORING_REASON_BR" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMP" ADD CONSTRAINT "FK_AMP_SUPPLIER" FOREIGN KEY ("CO_SUPPCD") REFERENCES "TD_SUPPLIER" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMPP" ADD CONSTRAINT "FK_AMPP_VMPP" FOREIGN KEY ("CO_VPPID") REFERENCES "TB_VMPP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMPP" ADD CONSTRAINT "FK_AMPP_AMP" FOREIGN KEY ("CO_APID") REFERENCES "TB_AMP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMPP" ADD CONSTRAINT "FK_AMPP_DISCONTINUED_IND" FOREIGN KEY ("CO_DISCCD") REFERENCES "TD_DISCONTINUED_IND" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMPP" ADD CONSTRAINT "FK_AMPP_LEGAL_CATEGORY" FOREIGN KEY ("CO_LEGAL_CATCD") REFERENCES "TD_LEGAL_CATEGORY" ("CO_SEQ_ID") ;
ALTER TABLE "TB_AMPP_GTIN" ADD CONSTRAINT "FK_AMPP_GTIN_AMPP" FOREIGN KEY ("CO_APPID") REFERENCES "TB_AMPP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_UNIT_OF_MEASURE_UDFS" FOREIGN KEY ("CO_UDFS_UOMCD") REFERENCES "TD_UNIT_OF_MEASURE" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_UNIT_OF_MEASURE_UNITDS" FOREIGN KEY ("CO_UNIT_DOSE_UOMCD") REFERENCES "TD_UNIT_OF_MEASURE" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_ANVS_CLASS_BR" FOREIGN KEY ("CO_ANVSCLSCD") REFERENCES "TD_ANVS_CLASS_BR" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_ATC_CLASS_BR" FOREIGN KEY ("CO_ATCCLSCD") REFERENCES "TD_ATC_CLASS_BR" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_BASIS_OF_NAME_BSCD" FOREIGN KEY ("CO_BASISCD") REFERENCES "TD_BASIS_OF_NAME" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_BASIS_OF_NAME_BSPREVCD" FOREIGN KEY ("CO_BASIS_PREVCD") REFERENCES "TD_BASIS_OF_NAME" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_DF_INDICATOR" FOREIGN KEY ("CO_DF_INDCD") REFERENCES "TD_DF_INDICATOR" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_NAME_CHANGE_REASON" FOREIGN KEY ("CO_NMCHANGECD") REFERENCES "TD_NAME_CHANGE_REASON" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_VIRTUAL_PROD_NON_AVAIL" FOREIGN KEY ("CO_NON_AVAILCD") REFERENCES "TD_VIRTUAL_PRODUCT_NON_AVAIL" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_VIRTUAL_PROD_PRES_STA" FOREIGN KEY ("CO_PRES_STATCD") REFERENCES "TD_VIRTUAL_PRODUCT_PRES_STATUS" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_VMP" FOREIGN KEY ("CO_VPIDPREV") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP" ADD CONSTRAINT "FK_VMP_VTM" FOREIGN KEY ("CO_VTMID") REFERENCES "TB_VTM" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMP_CATMAT_BR" ADD CONSTRAINT "FK_VMP_CATMAT_BR_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMPP" ADD CONSTRAINT "FK_VMPP_VMP" FOREIGN KEY ("CO_VPID") REFERENCES "TB_VMP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMPP" ADD CONSTRAINT "FK_VMPP_UNIT_OF_MEASURE" FOREIGN KEY ("CO_QTY_UOMCD") REFERENCES "TD_UNIT_OF_MEASURE" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VMPP_CATMAT_BR" ADD CONSTRAINT "FK_VMPP_CATMAT_BR_VMPP" FOREIGN KEY ("CO_VPPID") REFERENCES "TB_VMPP" ("CO_SEQ_ID") ;
ALTER TABLE "TB_VTM" ADD CONSTRAINT "FK_VTM_VTM" FOREIGN KEY ("CO_VTMIDPREV") REFERENCES "TB_VTM" ("CO_SEQ_ID") ;
ALTER TABLE "TD_ATC_CLASS_BR" ADD CONSTRAINT "FK_ATC_CLASS_BR_ATC_CLASS_BR" FOREIGN KEY ("CO_PARENT") REFERENCES "TD_ATC_CLASS_BR" ("CO_SEQ_ID") ;
ALTER TABLE "TD_FORM" ADD CONSTRAINT "FK_FORM_FORM_FFA" FOREIGN KEY ("CO_FFACD") REFERENCES "TD_FORM" ("CO_SEQ_ID") ;
ALTER TABLE "TD_FORM" ADD CONSTRAINT "FK_FORM_FORM" FOREIGN KEY ("CO_CDPREV") REFERENCES "TD_FORM" ("CO_SEQ_ID") ;
ALTER TABLE "TD_INGREDIENT_SUBSTANCES" ADD CONSTRAINT "FK_INGRD_SUBST_INGRD_SUBST" FOREIGN KEY ("CO_ISIDPREV") REFERENCES "TD_INGREDIENT_SUBSTANCES" ("CO_SEQ_ID") ;
ALTER TABLE "TD_INGREDIENT_SUBSTANCES" ADD CONSTRAINT "FK_INGR_SUBST_INGR_SOURCE_BR" FOREIGN KEY ("CO_ISRCID") REFERENCES "TD_INGREDIENT_SOURCE_BR" ("CO_SEQ_ID") ;
ALTER TABLE "TD_ROUTE" ADD CONSTRAINT "FK_ROUTE_ROUTE" FOREIGN KEY ("CO_CDPREV") REFERENCES "TD_ROUTE" ("CO_SEQ_ID") ;
ALTER TABLE "TD_SUPPLIER" ADD CONSTRAINT "FK_SUPPLIER_COUNTRY" FOREIGN KEY ("CO_COUNTRYCD") REFERENCES "TD_COUNTRY" ("CO_SEQ_ID") ;
ALTER TABLE "TD_SUPPLIER" ADD CONSTRAINT "FK_SUPPLIER_SUPPLIER" FOREIGN KEY ("CO_CDPREV") REFERENCES "TD_SUPPLIER" ("CO_SEQ_ID") ;
ALTER TABLE "TD_UNIT_OF_MEASURE" ADD CONSTRAINT "FK_UOM_UOM_CDPREV" FOREIGN KEY ("CO_CDPREV") REFERENCES "TD_UNIT_OF_MEASURE" ("CO_SEQ_ID") ;
